INSERT INTO RegularCustomers VALUES
/*   name   pizza bake  cut   sushi flavr bubbl donut sandw size bottm top  */
	('Trishna','ME', 'R', 'SQ', 'MM', 'PC', 'PP', 'DD', 'SK', 'M', 'BC', 'DF' ),
	('Xolo','CF', 'L', '6', 'KK', 'PC', 'KI', 'SP', 'BA', 'L', 'PB', 'SA' ),
	('Petrona','DE', 'L', '8', 'CB', 'PC', 'CH', 'DC', 'CH', 'S', 'TA', 'CS' ),
	('Boomer','QS', 'WD', 'SQ', 'SL', 'BL', 'BS', 'SP', 'CE', 'S', 'KI', 'DF' ),
	('Indigo','QS', 'L', '4', 'PX', 'PC', 'HB', 'TT', 'TP', 'L', 'SA', 'WA' ),
	('Santa',NULL, NULL, NULL, 'SC', 'SB', 'CU', 'NT', 'WJ', 'M', 'ST', 'DF' ),
	('Roy','DE', 'R', '8', 'SH', 'SB', 'CH', 'NT', 'CH', 'M', 'BU', 'LE' ),
	('Chester','PB', 'R', '4', 'CZ', 'TA', 'PP', 'CT', 'CO', 'M', 'TA', 'DF' ),
	('Mesa','SZ', 'WD', '8', 'PH', 'HD', 'CH', 'BZ', 'BM', 'L', 'DF', 'SA' ),
	('Sienna','SH', 'L', '8', 'TM', 'AL', 'SP', 'DB', 'BF', 'S', 'CS', 'ST' ),
	('Papa Louie','BC', 'L', '4', 'YO', 'AL', 'BS', 'BO', 'RS', 'L', 'SA', 'PB' ),
	('Didar','MA', 'L', '8', 'SA', 'AL', 'PP', 'BO', 'CP', 'S', 'ST', 'CS' ),
	('Skyler','FJ', 'L', '8', 'CZ', 'HD', 'SP', 'DM', 'FF', 'L', 'RB', 'BU' ),
	('Rudy','MU', 'WD', '4', 'VE', 'HD', 'CC', 'BC', 'CV', 'S', 'BC', 'BU' ),
	('Steven','ST', 'R', '6', 'YY', 'MA', 'KI', 'J2', 'PI', 'S', 'PI', 'BU' ),
	('Connor','RG', 'L', '6', 'SQ', 'BB', 'TA', 'SC', 'BZ', 'L', 'DF', 'BC' ),
	('Sarge Fan','MA', 'WD', '6', 'GS', 'PC', 'CC', 'WM', 'CA', 'L', 'LE', 'CS' ),
	('Hacky Zak','HA', 'R', 'SQ', 'SE', 'AL', 'CH', 'BA', 'WJ', 'L', 'BC', 'ST' ),
	('Akari','FC', 'R', '8', 'SC', 'TR', 'LY', 'CL', 'BF', 'M', 'SA', 'PI' ),
	('Sue','CL', 'WD', '6', 'PX', 'HD', 'SP', 'MM', 'CD', 'L', 'WA', 'DF' ),
	('Edna','SC', 'R', '6', 'RA', 'AL', 'WM', 'CE', 'BM', 'S', 'PI', 'KI' ),
	('Maggie','ME', 'R', 'SQ', 'RM', 'CH', 'KI', 'SP', 'BM', 'L', 'CS', 'BC' ),
	('Greg','LL', 'L', 'SQ', 'MM', 'AL', 'BS', 'GB', 'PU', 'L', 'TA', 'DF' ),
	('Kenji','CQ', 'WD', '8', 'UM', 'BL', 'CH', 'CP', 'PP', 'M', 'BR', 'LE' ),
	('Kaleb','OB', 'L', '6', 'OR', 'TR', 'MA', 'MM', 'SS', 'M', 'PI', 'ST' ),
	('Georgito','CA', 'WD', 'SQ', 'UM', 'BL', 'CH', 'DJ', 'MM', 'S', 'BC', 'PI' ),
	('Julep','CA', 'R', '8', NULL, NULL, NULL, 'DB', 'CA', 'M', 'KI', 'BR' ),
	('Little Edoardo','GG', 'R', '8', 'RA', 'SB', 'PP', 'ZF', 'CP', 'M', 'PI', 'CS' ),
	('Shannon','4M', 'R', '4', 'SL', 'TA', 'LY', 'J2', 'CH', 'S', 'CS', 'ST' ),
	('Captain Cori','HA', 'WD', 'SQ', 'CC', 'HD', 'HB', 'CS', 'CL', 'M', 'DF', 'TA' ),
	('Yui','SM', 'L', '8', 'ST', 'BB', 'HB', 'CP', 'RS', 'S', 'PI', 'CS' ),
	('Penny','CF', 'R', 'SQ', 'WW', 'TR', 'HB', 'SP', 'BZ', 'M', 'BR', 'KI' ),
	('Cecilia','PR', 'R', '4', 'TT', 'TR', 'CU', 'DS', 'CV', 'M', 'KI', 'PB' ),
	('Pinch Hitwell','MR', 'R', '8', 'FT', 'HD', 'CU', 'DT', 'HT', 'S', 'BU', 'TA' ),
	('Isadora','CS', 'L', '8', 'RM', 'BB', 'PP', 'CC', 'HT', 'S', 'LE', 'CS' ),
	('Bruna Romano','RG', 'WD', '8', 'SL', 'AL', 'HB', 'DS', 'PP', 'L', 'PB', 'PI' ),
	('Timm','CA', 'R', '8', 'NH', 'AL', 'TA', 'WM', 'CA', 'M', 'ST', 'RB' ),
	('Mindy','TB', 'L', '4', 'GE', 'MO', 'CU', 'PP', 'FB', 'S', 'RB', 'PI' ),
	('Koilee','CQ', 'WD', 'SQ', 'SP', 'MA', 'TA', 'TT', 'PP', 'S', 'BC', 'KI' ),
	('Rita','PB', 'R', '6', 'CP', 'MO', 'CU', 'CS', 'TT', 'M', 'KI', 'DF' ),
	('Kayla','FF', 'L', '8', 'YO', 'AL', 'LY', 'BE', 'TP', 'S', 'BC', 'KI' ),
	('Nye','OB', 'R', 'SQ', 'OR', 'SB', 'HB', 'AA', 'PP', 'S', 'WA', 'PB' ),
	('Elle','ST', 'WD', '8', 'VE', 'MA', 'SP', 'MM', 'SF', 'L', 'BR', 'ST' ),
	('Cooper','SM', 'R', '8', 'KK', 'BB', 'TA', 'DS', 'TP', 'S', 'ST', 'ST' ),
	('Budwin','TT', 'L', '8', NULL, NULL, NULL, 'AA', 'CV', 'L', 'BC', 'DF' ),
	('Rhonda','FF', 'WD', 'SQ', 'OR', 'TA', 'MA', 'FC', 'BQ', 'M', 'PI', 'BU' ),
	('Mandi','GG', 'R', '4', NULL, NULL, NULL, 'D1', 'BB', 'L', 'CS', 'ST' ),
	('Kenton','MU', 'L', '6', 'SC', 'PC', 'LY', 'DT', 'BR', 'S', 'WA', 'RB' ),
	('Clover','FG', 'L', 'SQ', 'KD', 'CH', 'CC', 'WM', 'BM', 'L', 'PI', 'RB' ),
	('Gremmie','SZ', 'L', '4', 'VE', 'TR', 'TA', 'FF', 'RS', 'L', 'BC', 'PB' ),
	('Tony','NE', 'WD', '6', 'KK', 'TA', 'TA', 'PP', 'RS', 'M', 'ST', 'CS' ),
	('Ninjoy','CF', 'L', '6', 'VE', 'MO', 'SP', 'RH', 'TP', 'S', 'WA', 'DF' ),
	('Wally','BC', 'R', 'SQ', 'SA', 'AL', 'BS', 'D1', 'BB', 'S', 'BC', 'ST' ),
	('Deano','PB', 'WD', 'SQ', 'CC', 'SB', 'KI', 'BO', 'BM', 'L', 'BU', 'WA' ),
	('Prudence','SM', 'WD', '6', 'FT', 'AL', 'CH', 'BC', 'CR', 'S', 'LE', 'BU' ),
	('Skip','SM', 'L', '6', 'CF', 'PC', 'CU', 'BO', 'SS', 'M', 'LE', 'KI' ),
	('Yuko','TT', 'WD', '4', 'SB', 'SB', 'KI', 'MM', 'CH', 'M', 'PI', 'LE' ),
	('Moe','WO', 'WD', '6', 'RA', 'TR', 'SP', 'TT', 'BV', 'S', 'RB', 'LE' ),
	('Wylan B','SR', 'WD', '8', 'CF', 'BL', 'CU', 'SP', 'FB', 'S', 'ST', 'LE' ),
	('Treble','RG', 'R', 'SQ', 'KD', 'BL', 'CU', 'AA', 'WJ', 'M', 'PB', 'DF' ),
	('WhiffAmy','QS', 'WD', '8', 'WW', 'PC', 'LY', 'ZF', 'JS', 'M', 'SA', 'BU' ),
	('Liezel','TT', 'WD', '4', 'MM', 'TA', 'KI', 'BA', 'CE', 'S', 'BU', 'SA' ),
	('Wendy','BC', 'R', '8', 'TM', 'TR', 'CC', 'GB', 'TT', 'M', 'DF', 'SA' ),
	('Bertha','NE', 'R', '6', 'AJ', 'AL', 'TA', 'TT', 'BV', 'L', 'PB', 'LE' ),
	('Boopsy & Bill','SC', 'WD', '8', 'SS', 'HD', 'SP', 'CP', 'WJ', 'S', 'CS', 'KI' ),
	('Jojo','WO', 'WD', '8', 'YY', 'BL', 'WM', 'J2', 'TP', 'S', 'WA', 'ST' ),
	('Cameo','NE', 'WD', '6', 'MM', 'HD', 'TA', 'DD', 'BA', 'L', 'LE', 'BC' ),
	('Nevada','BC', 'R', '4', 'SP', 'MO', 'CC', 'CL', 'FB', 'L', 'CS', 'BR' ),
	('Simone','NE', 'L', '4', 'VE', 'BL', 'TA', 'D1', 'CV', 'M', 'BC', 'RB' ),
	('Chuck','SH', 'WD', '4', 'GS', 'PC', 'CH', 'CL', 'BQ', 'L', 'DF', 'WA' ),
	('Scarlett','SZ', 'R', '8', 'CR', 'MO', 'LY', 'DJ', 'TP', 'S', 'BC', 'BU' ),
	('Cherissa','4M', 'R', 'SQ', 'SS', 'SB', 'SP', 'MM', 'SK', 'M', 'BR', 'RB' ),
	('Emmlette','MA', 'R', '6', 'GS', 'MO', 'CC', 'SS', 'CL', 'M', 'TA', 'PI' ),
	('Robby','4M', 'L', '6', 'CP', 'CH', 'SP', 'AA', 'BA', 'L', 'BC', 'BU' ),
	('Ripley','GF', 'WD', 'SQ', 'CP', 'HD', 'KI', 'ZF', 'PP', 'S', 'DF', 'LE' ),
	('Sasha','CQ', 'R', 'SQ', 'CZ', 'CH', 'MA', 'ZF', 'CP', 'M', 'PI', 'BR' ),
	('Hope','SM', 'WD', 'SQ', 'GE', 'BB', 'MA', 'RL', 'PI', 'L', 'PI', 'SA' ),
	('Whippa','LF', 'WD', '4', 'OR', 'MO', 'BS', 'J2', 'SS', 'S', 'KI', 'DF' ),
	('Rico','GG', 'R', '8', 'TE', 'BB', 'TA', 'D1', 'PI', 'L', 'TA', 'TA' ),
	('Alberto','SM', 'R', '6', 'LL', 'BL', 'CU', 'FC', 'TT', 'S', 'BU', 'PB' ),
	('Utah','PR', 'R', 'SQ', 'KD', 'SB', 'CC', 'CE', 'BZ', 'S', 'PB', 'PI' ),
	('Scooter','MR', 'WD', '4', 'NH', 'MA', 'PP', 'CU', 'SK', 'S', 'TA', 'DF' ),
	('Duke Gotcha','PC', 'R', '4', 'PH', 'BB', 'BS', 'DC', 'FB', 'M', 'BR', 'ST' ),
	('Rollie','HA', 'WD', '6', 'BQ', 'TA', 'WM', 'SS', 'KC', 'M', 'PI', 'DF' ),
	('Lisa','MA', 'L', '6', 'ST', 'PC', 'WM', 'WM', 'HM', 'S', 'SA', 'LE' ),
	('Fernanda','GG', 'WD', '6', 'SA', 'BL', 'KI', 'WM', 'HP', 'L', 'LE', 'BC' ),
	('Xandra','GF', 'L', '8', 'GS', 'AL', 'PP', 'CS', 'FB', 'M', 'WA', 'PI' ),
	('Taylor',NULL, NULL, NULL, 'SS', 'SB', 'BS', 'JD', 'FM', 'S', 'DF', 'BR' ),
	('Brody','GF', 'R', '6', 'SP', 'SB', 'SP', 'GB', 'CO', 'S', 'BC', 'BR' ),
	('Franco',NULL, NULL, NULL, 'TM', 'PC', 'KI', 'RR', 'CA', 'M', 'PB', 'BC' ),
	('Nick','SG', 'R', 'SQ', 'TE', 'AL', 'HB', 'RR', 'BM', 'M', 'TA', 'DF' ),
	('Sprinks the Clown','CS', 'R', 'SQ', 'RM', 'AL', 'BS', 'SP', 'BB', 'L', 'BC', 'PI' ),
	('Vicky','SM', 'R', 'SQ', 'YY', 'AL', 'TA', 'BE', 'HM', 'M', 'BR', 'TA' ),
	('Cletus','QS', 'WD', '6', 'SE', 'TR', 'SP', 'FF', 'CO', 'M', 'BC', 'ST' ),
	('Quinn','SZ', 'L', 'SQ', 'TE', 'CH', 'TA', 'CL', 'HT', 'L', 'TA', 'PB' ),
	('Olga','CS', 'WD', 'SQ', 'CR', 'MA', 'MA', 'CC', 'TT', 'M', 'BU', 'LE' ),
	('Chase','CL', 'L', '4', 'WW', 'MO', 'TA', 'RR', 'MM', 'M', 'SA', 'SA' ),
	('Allan','SG', 'L', '4', 'CZ', 'MA', 'KI', 'BZ', 'FF', 'L', 'PB', 'WA' ),
	('Austin','CQ', 'WD', 'SQ', 'SC', 'CH', 'PP', 'FF', 'FM', 'M', 'KI', 'BC' ),
	('Foodini','BC', 'R', '4', 'OR', 'SB', 'WM', 'CT', 'SS', 'M', 'SA', 'RB' ),
	('C.J. Frisksns','MA', 'L', '8', 'SB', 'HD', 'MA', 'DM', 'BV', 'L', 'PB', 'DF' ),
	('Mitch','FF', 'R', '6', 'KR', 'MO', 'SP', 'BA', 'HM', 'M', 'PI', 'DF' ),
	('Evelyn',NULL, NULL, NULL, 'SQ', 'MO', 'HB', 'RR', 'NV', 'S', 'LE', 'KI' ),
	('Amiria','RG', 'L', '4', 'TE', 'BB', 'CH', 'JL', 'CV', 'S', 'LE', 'ST' ),
	('Hugo','GF', 'WD', '8', 'FT', 'MA', 'WM', 'DC', 'BZ', 'S', 'RB', 'ST' ),
	('Iggy','GG', 'R', '6', 'RM', 'TA', 'KI', 'FC', 'CH', 'L', 'WA', 'PB' ),
	('Mayor Mallow','QS', 'WD', '6', 'FT', 'CH', 'BS', 'DC', 'NV', 'S', 'RB', 'RB' ),
	('Carlo Romano','CF', 'R', '4', 'RA', 'BB', 'MA', 'CS', 'BV', 'L', 'DF', 'BR' ),
	('Kahuna',NULL, NULL, NULL, 'SH', 'HD', 'SP', 'JL', 'SK', 'S', 'BR', 'PI' ),
	('Doan','HA', 'WD', '4', 'TE', 'AL', 'LY', 'SS', 'NV', 'M', 'TA', 'PB' ),
	('Clair','FF', 'R', '4', 'PH', 'TR', 'CU', 'BC', 'BQ', 'M', 'RB', 'SA' ),
	('LePete','CS', 'R', 'SQ', 'SS', 'TR', 'HB', 'VS', NULL, NULL, NULL, NULL ),
	('Kasey O','WO', 'L', '4', 'TM', 'AL', 'WM', 'JL', 'BR', 'M', 'BC', 'ST' ),
	('Matt','GF', 'R', '8', 'OR', 'BB', 'HB', 'BO', 'BF', 'M', 'PB', 'BC' ),
	('Kingsley','SZ', 'WD', '6', 'SE', 'CH', 'KI', 'PP', 'BA', 'L', 'BU', 'PB' ),
	('Perri','TT', 'R', '6', 'SH', 'TR', 'TA', 'TT', 'NV', 'L', 'WA', 'BC' ),
	('Janana','CQ', 'WD', '8', 'KR', 'TR', 'CH', 'RH', 'CE', 'S', 'WA', 'SA' ),
	('Professor Fitz','DE', 'R', '6', 'ST', 'TA', 'MA', 'DB', 'HT', 'L', 'WA', 'ST' ),
	('Tohru','4M', 'R', '6', 'BQ', 'AL', 'WM', 'CT', 'RS', 'L', 'PI', 'BU' ),
	('Gino Romano','RG', 'R', '8', 'TM', 'SB', 'KI', 'DM', 'HT', 'L', 'PI', 'KI' ),
	('Olivia','LL', 'WD', '6', 'SA', 'AL', 'WM', 'CL', 'PU', 'M', 'LE', 'RB' ),
	('Zoe','CA', 'WD', 'SQ', 'SC', 'AL', 'KI', 'BZ', 'FF', 'M', 'TA', 'KI' ),
	('Mary','4M', 'L', 'SQ', 'PX', 'AL', 'SP', 'BE', 'SK', 'L', 'WA', 'BR' ),
	('Okalani','FJ', 'WD', '6', 'SB', 'HD', 'WM', 'CT', 'HP', 'M', 'BC', 'LE' ),
	('Ember','DE', 'R', '8', 'VE', 'BL', 'SP', 'BA', 'PP', 'M', 'ST', 'CS' ),
	('Big Pauly','CS', 'L', '8', 'CZ', 'CH', 'WM', 'CU', 'PP', 'M', 'RB', 'KI' ),
	('Ivy','OB', 'WD', '4', 'SH', 'SB', 'BS', 'CC', 'CA', 'L', 'RB', 'CS' ),
	('Vincent','CS', 'R', '6', 'SH', 'BL', 'LY', 'CC', 'SS', 'L', 'LE', 'PB' ),
	('Willow','NE', 'R', '8', 'SE', 'MO', 'BS', 'CC', 'CO', 'L', 'WA', 'KI' ),
	('Marty','SC', 'WD', '6', 'TT', 'HD', 'TA', 'MM', 'TP', 'S', 'TA', 'CS' ),
	('Daniela','MA', 'WD', '4', 'CB', 'TR', 'PP', 'BE', 'PP', 'L', 'LE', 'LE' ),
	('Mousse','WO', 'WD', '8', 'SE', 'PC', 'CH', 'RH', 'CP', 'M', 'SA', 'BC' ),
	('Peggy','SZ', 'WD', '8', 'PX', 'HD', 'LY', 'CS', 'PU', 'S', 'TA', 'CS' ),
	('Joy','BC', 'WD', '6', 'LL', 'TR', 'KI', 'FC', 'HM', 'L', 'BR', 'DF' ),
	('Johnny','CF', 'R', 'SQ', 'SP', 'MO', 'LY', 'RR', 'JS', 'L', 'SA', 'CS' ),
	('Mr. Bombolony','MU', 'L', '4', 'SS', 'TR', 'CU', 'FF', 'CO', 'S', 'RB', 'PB' ),
	('Crystal','MA', 'L', '6', 'CZ', 'CH', 'CC', 'FC', 'SF', 'M', 'LE', 'PI' ),
	('Hank','ST', 'R', '8', 'CB', 'HD', 'KI', 'D1', 'NV', 'M', 'KI', 'WA' ),
	('Yippy','WO', 'R', 'SQ', 'FT', 'AL', 'MA', 'J2', 'FF', 'M', 'BR', 'DF' ),
	('Pally','PR', 'L', '4', 'KR', 'MA', 'CC', 'BO', 'BM', 'L', 'LE', 'CS' ),
	('Radlynn','ST', 'WD', '4', 'CR', 'BL', 'LY', 'DT', 'SK', 'S', 'RB', 'KI' ),
	('James','FF', 'R', '8', 'TE', 'CH', 'KI', 'DS', 'SK', 'M', 'BC', 'BU' ),
	('Drakson','SH', 'R', '6', 'LL', 'AL', 'HB', 'DT', 'CP', 'L', 'BC', 'BU' )
